In [1]:
import pandas as pd
import numpy as np

In [2]:
oddsDf = pd.read_csv('nbaOdds.csv')
resultsDf = pd.read_csv('nbaResults.csv')

oddsDf.drop(columns=['sport','gameState'],inplace=True)


print(oddsDf.shape)
print(resultsDf.shape)

(274, 20)
(195, 26)

In [3]:
new_res = resultsDf[pd.isna(resultsDf.awayTeam)==False].copy()
resultsDf = resultsDf[pd.isna(resultsDf.awayTeam)].copy()

In [4]:
resultsDf.columns

Index(['AwayDiff', 'AwayOutcome', 'AwayTeam', 'Date_Time', 'Game_State',
       'HomeDiff', 'HomeOutcome', 'HomeTeam', 'Sb_id', 'Score', 'Sport',
       'Total', '__id__', 'id', 'awayDiff', 'awayOutcome', 'awayTeam',
       'dateTime', 'gameState', 'homeDiff', 'homeOutcome', 'homeTeam', 'sbId',
       'score', 'sport', 'total'],
      dtype='object')

In [5]:
new_res.drop(columns=['AwayDiff', 'AwayOutcome', 'AwayTeam', 'Date_Time', 'Game_State',
       'HomeDiff', 'HomeOutcome', 'HomeTeam', 'Sb_id', 'Score', 'Sport',
       'Total'],inplace=True)
resultsDf.drop(columns=['awayDiff', 'awayOutcome', 'awayTeam',
       'dateTime', 'gameState', 'homeDiff', 'homeOutcome', 'homeTeam', 'sbId',
       'score', 'sport', 'total'],inplace=True)

In [6]:
resultsDf.columns
resultsDf.rename(columns = {'AwayDiff':'awayDiff', 'AwayOutcome':'awayOutcome', 'AwayTeam':'awayTeam', 
                            'Date_Time':'dateTime', 'Game_State':'gameState','HomeDiff':'homeDiff', 
                            'HomeOutcome':'homeOutcome', 'HomeTeam':'homeTeam', 'Sb_id':'sbId', 'Score':'score',
                            'Sport':'sport','Total':'total'}, inplace=True)

In [7]:
oddsDf.rename(columns = {'AwayTeam':'awayTeam', 'Away_Odds':'awayOdds', 'Away_Spread':'awaySpread', 
                         'Away_Spread_Odds':'awaySpreadOdds', 'Book_Odds':'bookOdds', 'Consensus':'consensus', 
                         'Date_Time':'dateTime', 'Game_State':'gameState', 'HomeTeam':'homeTeam', 
                         'Home_Odds':'homeOdds','Home_Spread':'homeSpread', 'Home_Spread_Odds':'homeSpreadOdds',
                         'Over':'over', 'Over_Odds':'overOdds', 'Sb_id':'sbId',
                        'Sport':'sport', 'Under':'under', 'Under_Odds':'underOdds',}, inplace=True)

In [8]:
resultsDf.shape

(155, 14)

In [9]:
new_res.shape

(40, 14)

In [10]:
resultsDf = pd.concat([resultsDf,new_res])

In [11]:
### basic cleaning
oddsDf.drop(columns=['bookOdds','consensus','homeTeam','awayTeam','sbId','gameState','id','sport'],inplace=True)
resultsDf.drop(columns=['dateTime'],inplace=True)

In [12]:
oddsDf.head(5)

,awayOdds,awaySpread,awaySpreadOdds,dateTime,homeOdds,homeSpread,homeSpreadOdds,over,overOdds,under,underOdds,__id__
0,-125,-2.5,100,2022-04-02T19:30:00,125,2.5,100,241.0,100,241.0,100,ATLBKN422022
1,190,5.5,100,2022-04-13T19:00:00,-190,-5.5,100,235.5,100,235.5,100,ATLCHA4132022
2,205,6.0,100,2022-03-31T19:30:00,-205,-6.0,100,230.0,100,230.0,100,ATLCLE3312022
3,125,2.5,100,2022-03-25T19:30:00,-125,-2.5,100,221.5,100,221.5,100,ATLGS3252022
4,590,12.0,100,2022-03-13T19:00:00,-590,-12.0,100,237.0,100,237.0,100,ATLIND3132022

In [13]:
nbaData = resultsDf.merge(oddsDf, on='__id__')

In [14]:
nbaData.to_csv('allNbaData.csv')

In [17]:
nbaData

,awayDiff,awayOutcome,awayTeam,gameState,homeDiff,homeOutcome,homeTeam,sbId,score,sport,...,awaySpread,awaySpreadOdds,dateTime,homeOdds,homeSpread,homeSpreadOdds,over,overOdds,under,underOdds
0,-11.0,L,Golden State Warriors,Final,11.0,W,Atlanta Hawks,17793.0,121-110,NBA,...,2.5,100,2022-03-25T19:30:00,-125,-2.5,100,221.5,100,221.5,100
1,-3.0,L,Indiana Pacers,Final,3.0,W,Atlanta Hawks,17707.0,131-128,NBA,...,12.0,100,2022-03-13T19:00:00,-590,-12.0,100,237.0,100,237.0,100
2,-6.0,L,Los Angeles Clippers,Final,6.0,W,Atlanta Hawks,17687.0,112-106,NBA,...,7.5,100,2022-03-11T19:30:00,-250,-7.5,100,226.5,100,226.5,100
3,-15.0,L,Memphis Grizzlies,Final,15.0,W,Atlanta Hawks,17738.0,120-105,NBA,...,-5.5,100,2022-03-18T19:30:00,185,5.5,100,237.5,100,237.5,100
4,5.0,W,New Orleans Pelicans,Final,-5.0,L,Atlanta Hawks,17755.0,112-117,NBA,...,3.5,100,2022-03-20T18:00:00,-145,-3.5,100,233.0,100,233.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,-24.0,L,Atlanta Hawks,Final,24.0,W,Miami Heat,18057.0,115-91,NBA,...,7.0,100,2022-04-17T13:00:00,-240,-7.0,100,219.5,100,219.5,100
162,-7.0,L,Chicago Bulls,Final,7.0,W,Milwaukee Bucks,18016.0,93-86,NBA,...,10.5,100,2022-04-17T18:30:00,-450,-10.5,100,230.0,100,230.0,100
163,-20.0,L,Toronto Raptors,Final,20.0,W,Philadelphia 76ers,18014.0,131-111,NBA,...,4.5,100,2022-04-16T18:00:00,-170,-4.5,100,216.0,100,216.0,100
164,-15.0,L,Toronto Raptors,Final,15.0,W,Philadelphia 76ers,18019.0,112-97,NBA,...,7.0,100,2022-04-18T19:30:00,-245,-7.0,100,218.0,100,218.0,100
165,-11.0,L,New Orleans Pelicans,Final,11.0,W,Phoenix Suns,18058.0,110-99,NBA,...,10.5,100,2022-04-17T21:00:00,-445,-10.5,100,224.0,100,224.0,100